"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

//! --- React Query dependencies --- //

import {
    QueryClient,
    QueryClientProvider,
    useQuery,
} from "@tanstack/react-query";

const queryClient = new QueryClient();

//! ----------------------------------

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="bumblebee">
            <QueryClientProvider client={queryClient}>
                <body className={inter.className}>
                    <Header />

                    {children}
                    <Footer />
                </body>
            </QueryClientProvider>
        </html>
    );
}
